In [4]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import folium
import mapclassify
from census import Census
import us
from us import states
import os

In [5]:
MY_API_KEY= 'your api key'

wa_census_house_price = Census(MY_API_KEY).acs5.state_county_tract(fields = ('NAME', 'B25104_001E', 'B25104_002E', 'B25104_003E', 'B25104_004E', 'B25104_005E', 'B25104_006E', 'B25104_007E', 'B25104_008E', 'B25104_009E', 'B25104_010E', 'B25104_011E', 'B25104_012E', 'B25104_013E', 'B25104_014E', 'B25104_015E', 'B25104_016E', 'B25104_017E'),
                                      state_fips = states.WA.fips,
                                      county_fips = "*",
                                      tract = "*",
                                      year = 2021)

In [6]:
# Create a dataframe from the census data
wa_house_cost_df = pd.DataFrame(wa_census_house_price)

# Show the dataframe
wa_house_cost_df.shape

(1784, 21)

In [7]:
wa_house_cost_df.head()

,NAME,B25104_001E,B25104_002E,B25104_003E,B25104_004E,B25104_005E,B25104_006E,B25104_007E,B25104_008E,B25104_009E,...,B25104_011E,B25104_012E,B25104_013E,B25104_014E,B25104_015E,B25104_016E,B25104_017E,state,county,tract
0,"Census Tract 9501, Adams County, Washington",1040.0,2.0,28.0,30.0,74.0,72.0,125.0,62.0,153.0,...,90.0,207.0,56.0,17.0,2.0,16.0,57.0,53,001,950100
1,"Census Tract 9502, Adams County, Washington",564.0,0.0,18.0,42.0,67.0,56.0,42.0,38.0,29.0,...,40.0,91.0,39.0,7.0,0.0,2.0,53.0,53,001,950200
2,"Census Tract 9503.01, Adams County, Washington",569.0,30.0,0.0,0.0,58.0,62.0,21.0,40.0,100.0,...,43.0,86.0,10.0,14.0,0.0,20.0,69.0,53,001,950301
3,"Census Tract 9503.02, Adams County, Washington",753.0,0.0,7.0,42.0,36.0,71.0,138.0,26.0,118.0,...,100.0,63.0,51.0,19.0,0.0,0.0,19.0,53,001,950302
4,"Census Tract 9503.03, Adams County, Washington",682.0,0.0,0.0,46.0,6.0,249.0,160.0,22.0,7.0,...,19.0,32.0,37.0,78.0,5.0,12.0,9.0,53,001,950303

In [8]:
wa_house_cost_df.to_csv('path_to_file.csv', index=False)